Miniproyecto/Miniproyecto/Controllers/SeriesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MiniProyecto.BLL.Contracts;
using MiniProyecto.BLL.Models;
using MiniProyecto.DAL.Entities;
using MiniProyecto.DAL.Interfaces;
using MiniProyecto.Web.Models;
using System.Collections.Generic;

namespace Miniproyecto.Web.Controllers
{
    public class SeriesController : Controller
    {
        private readonly ISeriesService _serieService;
        private readonly ICategoriaService _categoriaService;
        private readonly IGeneroService _generoService;
        private readonly IProductorService _productorService;

        public SeriesController(ISeriesService serieService, ICategoriaService categoriaService, IGeneroService generoService, IProductorService productorService)
        {
            _serieService = serieService;
            _categoriaService = categoriaService;
            _generoService = generoService;
            _productorService = productorService;
        }

        // GET: SerieController
        public ActionResult Index()
        {
            var serieData = _serieService.GetAll().Data as List<MiniProyecto.BLL.Models.SeriesModel>;
           var serieModels = new List<MiniProyecto.Web.Models.SeriesModel>();

            if (serieData != null)
            {
                serieModels = serieData.Select(s => new MiniProyecto.Web.Models.SeriesModel
                {
                    SerieID = s.SerieID,
                    Nombre = s.Nombre,
                    Descripcion = s.Descripcion,
                    Imagen = s.Imagen,
                    IDcategoria = s.IDcategoria,
                    IDproductor = s.IDproductor,
                    IDgenero = s.IDgenero,
                    IDgenero2 = s.IDgenero2,
                    URL = s.URL
                    
                }).ToList();
            }

            return View(serieModels);
        }

        // GET: SerieController/Details/5
        public ActionResult Details(int id)
        {
            var serieResult = _serieService.GetById(id);
            if (serieResult.Success)
            {
                var serie = (MiniProyecto.BLL.Models.SeriesModel)serieResult.Data;
                var serieViewModel = new MiniProyecto.Web.Models.SeriesModel()
                {
                    SerieID = serie.SerieID,
                    Nombre = serie.Nombre,
                    Descripcion = serie.Descripcion,
                    Imagen = serie.Imagen,
                    IDcategoria = serie.IDcategoria,
                    IDproductor = serie.IDproductor,
                    IDgenero = serie.IDgenero,
                    IDgenero2 = serie.IDgenero2,
                    URL = serie.URL

                };
                return View(serieViewModel);
            }
            else
            {
                return View("Serie no encontrada");
            }
        }

        // GET: SerieController/Create
        public ActionResult Create()
        {
            ViewBag.Categorias = _categoriaService.GetAll().Data;
            ViewBag.Generos = _generoService.GetAll().Data;
            ViewBag.Productores = _productorService.GetAll().Data;
            return View();
        }

        // POST: SerieController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MiniProyecto.DAL.Entities.Series serie)
        {
            try
            {
                MiniProyecto.BLL.Dtos.SeriesDTO serieToSave = new MiniProyecto.BLL.Dtos.SeriesDTO()
                {
                    SerieID = serie.SerieID,
                    Nombre = serie.Nombre,
                    Descripcion = serie.Descripcion,
                    Imagen = serie.Imagen,
                    IDcategoria = serie.IDcategoria,
                    IDproductor = serie.IDproductor,
                    IDgenero = serie.IDgenero,
                    IDgenero2 = serie.IDgenero2,
                    URL = serie.URL

                };
                _serieService.Save(serieToSave);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SerieController/Edit/5
        public ActionResult Edit(int id)
        {
            var serieResult = _serieService.GetById(id);
            if (serieResult.Success)
            {
                var serie = (MiniProyecto.BLL.Models.SeriesModel)serieResult.Data;
                var serieViewModel = new MiniProyecto.Web.Models.SeriesModel()
                {
                    SerieID = serie.SerieID,
                    Nombre = serie.Nombre,
                    Descripcion = serie.Descripcion,
                    Imagen = serie.Imagen,
                    IDcategoria = serie.IDcategoria,
                    IDproductor = serie.IDproductor,
                    IDgenero = serie.IDgenero,
                    IDgenero2 =serie.IDgenero2,
                          URL = serie.URL

                };
                ViewBag.Categorias = _categoriaService.GetAll().Data;
                ViewBag.Generos = _generoService.GetAll().Data;
                ViewBag.Productores = _productorService.GetAll().Data;
                return View(serieViewModel);
            }
            else
            {
                return View("Serie no encontrada");
            }
        }

        // POST: SerieController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, MiniProyecto.Web.Models.SeriesModel serie)
        {
            try
            {
                MiniProyecto.BLL.Dtos.SeriesDTO serieToUpdate = new MiniProyecto.BLL.Dtos.SeriesDTO()
                {
                    SerieID = serie.SerieID,
                    Nombre = serie.Nombre,
                    Descripcion = serie.Descripcion,
                    Imagen = serie.Imagen,
                    IDcategoria = serie.IDcategoria,
                    IDproductor = serie.IDproductor,
                    IDgenero = serie.IDgenero,
                    IDgenero2 = serie.IDgenero2,
                    URL = serie.URL
                    
                };
                _serieService.Update(serieToUpdate);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SerieController/Delete/5
        public ActionResult Delete(int id)
        {
            var serieResult = _serieService.GetById(id);
            if (serieResult.Success)
            {
                var serie = (MiniProyecto.BLL.Models.SeriesModel)serieResult.Data;
                var serieViewModel = new MiniProyecto.Web.Models.SeriesModel()
                {
                    SerieID = serie.SerieID,
                    Nombre = serie.Nombre,
                    Descripcion = serie.Descripcion,
                    Imagen = serie.Imagen,
                    IDcategoria = serie.IDcategoria,
                    IDproductor = serie.IDproductor,
                    IDgenero = serie.IDgenero,
                    IDgenero2 = serie.IDgenero2,
                          URL = serie.URL
                };
                return View(serieViewModel);
            }
            else
            {
                return View("Serie no encontrada");
            }
        }

        // POST: SerieController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, MiniProyecto.Web.Models.SeriesModel serie)
        {
            try
            {
                MiniProyecto.BLL.Dtos.SeriesDTO seriesDTO = new MiniProyecto.BLL.Dtos.SeriesDTO
                {
                    IDcategoria = serie.IDcategoria,
                    IDgenero = serie.IDgenero,
                    Descripcion = serie.Descripcion,
                    IDproductor = serie.IDproductor,
                    Imagen = serie.Imagen,
                    SerieID = serie.SerieID,
                    Nombre = serie.Nombre,
                    IDgenero2 = serie.IDgenero2,
                    URL = serie.URL


                };
                _serieService.Remove(seriesDTO);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Miniproyecto/Miniproyecto/Views/Series/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    var categorialista = ViewBag.Categorias;
    var productoralista = ViewBag.Productores;
    var generolista = ViewBag.Generos;
}
@model MiniProyecto.DAL.Entities.Series
<!DOCTYPE html>
<html>
<head>
    <title>Series Management</title>
    <style>
        /* Estilos generales */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #1a1a1a;
            color: #fff;
        }

        /* Contenido principal */
        main {
            padding: 20px;
            width: 100%;
            box-sizing: border-box;
        }

        /* Listado de series */
        .series-list {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
            gap: 20px;
        }

        .series-item {
            background-color: #262626;
            padding: 20px;
            text-align: center;
        }

            .series-item img {
                max-width: 100%;
                height: auto;
                margin-bottom: 20px;
            }

            .series-item h3 {
                margin-bottom: 10px;
            }

            .series-item p {
                margin-bottom: 20px;
            }

            .series-item button {
                background-color: #E50914;
                color: #fff;
                border: none;
                padding: 10px 20px;
                font-size: 16px;
                cursor: pointer;
                margin-right: 10px;
            }

        /* Formulario de creación/edición */
        .form-container {
            background-color: #262626;
            padding: 20px;
        }

            .form-container form {
                display: grid;
                grid-template-columns: 1fr 1fr;
                gap: 20px;
            }

            .form-container label {
                display: block;
                margin-bottom: 5px;
            }

            .form-container input,
            .form-container select {
                width: 100%;
                padding: 10px;
                font-size: 16px;
                background-color: #1a1a1a;
                color: #fff;
                border: none;
            }

            .form-container button {
                background-color: #E50914;
                color: #fff;
                border: none;
                padding: 10px 20px;
                font-size: 16px;
                cursor: pointer;
                margin-right: 10px;
            }

            .form-container a {
                background-color: #E50914;
                color: #fff;
                border: none;
                padding: 10px 20px;
                font-size: 16px;
                cursor: pointer;
                margin-right: 10px;
            }
    </style>
</head>
<body>

    <main>



        <!-- Sección de creación/edición de series -->
        <div class="form-container">
            <h2>Crear Serie</h2>
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div>
                    <label asp-for="Nombre">Nombre de la serie:</label>
                    <input asp-for=Nombre type="text" id="name " name="Nombre" required>
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
                <div>
                    <label asp-for="Imagen">Imagen de portada:</label>
                    <input asp-for=Imagen type="text" id="cover-image" name="Imagen" required>
                    <span asp-validation-for="Imagen" class="text-danger"></span>
                </div>
                <div>
                    <label asp-for="URL">Enlace del video de YouTube:</label>
                    <input asp-for=URL type="text" id="youtube-link" name="URL" required>
                    <span asp-validation-for="URL" class="text-danger"></span>
                </div>
                <div>
                    <label for="production-company">Productora:</label>
                    <select asp-items="@(new SelectList(ViewBag.Productores, "IDproductor","Nombre"))" id="secondary-genre" name="IDproductor">
                        <!-- Agrega más opciones de productoras -->
                    </select>
                    <span asp-validation-for="IDproductor" class="text-danger"></span>
                </div>
                <div>
                    <label for="primary-genre">Género primario:</label>
                    <select asp-items="@(new SelectList(ViewBag.Generos, "IDgenero","Tipo"))" id="secondary-genre" name="IDgenero">

                        <!-- Agrega más opciones de géneros -->
                    </select>
                    <span asp-validation-for="IDgenero" class="text-danger"></span>
                </div>
                <div>
                    <label for="secondary-genre">Género secundario:</label>
                    <select asp-items="@(new SelectList(ViewBag.Generos, "IDgenero","Tipo"))" id="secondary-genre" name="IDgenero2">

                        <!-- Agrega más opciones de géneros -->
                    </select>
                    <span asp-validation-for="IDgenero2" class="text-danger"></span>
                </div>
                <div>
                    <label for="name">Descripcion:</label>
                    <input asp-for=Descripcion type="text" id="decripcion" name="Descripcion" required>
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>
                <div>
                    <label for="primary-genre">Categoria :</label>
                    <select asp-items="@(new SelectList(ViewBag.Categorias, "IDcategoria", "Nombre"))" id="secondary-genre" name="IDcategoria">

                        <!-- Agrega más opciones de géneros -->
                    </select>
                    <span asp-validation-for="IDcategoria" class="text-danger"></span>
                </div>
                <div>
                    <a asp-controller="Series" asp-action="index" class="btn btn-primary">Volver</a>
                    <button type="submit" value="Create">Crear Serie</button>
                </div>
            </form>
        </div>
    </main>
</body>
</html>

Miniproyecto/Miniproyecto/Views/Series/Create2.cshtml
@model MiniProyecto.DAL.Entities.Series

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Series</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SerieID" class="control-label"></label>
                <input asp-for="SerieID" class="form-control" />
                <span asp-validation-for="SerieID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="URL" class="control-label"></label>
                <input asp-for="URL" class="form-control" />
                <span asp-validation-for="URL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IDcategoria" class="control-label"></label>
                <input asp-for="IDcategoria" class="form-control" />
                <span asp-validation-for="IDcategoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IDproductor" class="control-label"></label>
                <input asp-for="IDproductor" class="form-control" />
                <span asp-validation-for="IDproductor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IDgenero" class="control-label"></label>
                <input asp-for="IDgenero" class="form-control" />
                <span asp-validation-for="IDgenero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IDgenero2" class="control-label"></label>
                <input asp-for="IDgenero2" class="form-control" />
                <span asp-validation-for="IDgenero2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Miniproyecto/Miniproyecto/Views/Series/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    var categorialista = ViewBag.Categorias;
    var productoralista = ViewBag.Productores;
    var generolista = ViewBag.Generos;
}
@model MiniProyecto.Web.Models.SeriesModel
<!DOCTYPE html>
<html>
<head>
    <title>Series Management</title>
    <style>
        /* Estilos generales */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #1a1a1a;
            color: #fff;
        }

        /* Contenido principal */
        main {
            padding: 20px;
            width: 100%;
            box-sizing: border-box;
        }

        /* Listado de series */
        .series-list {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
            gap: 20px;
        }

        .series-item {
            background-color: #262626;
            padding: 20px;
            text-align: center;
        }

            .series-item img {
                max-width: 100%;
                height: auto;
                margin-bottom: 20px;
            }

            .series-item h3 {
                margin-bottom: 10px;
            }

            .series-item p {
                margin-bottom: 20px;
            }

            .series-item button {
                background-color: #E50914;
                color: #fff;
                border: none;
                padding: 10px 20px;
                font-size: 16px;
                cursor: pointer;
                margin-right: 10px;
            }

        /* Formulario de creación/edición */
        .form-container {
            background-color: #262626;
            padding: 20px;
        }

            .form-container form {
                display: grid;
                grid-template-columns: 1fr 1fr;
                gap: 20px;
            }

            .form-container label {
                display: block;
                margin-bottom: 5px;
            }

            .form-container input,
            .form-container select {
                width: 100%;
                padding: 10px;
                font-size: 16px;
                background-color: #1a1a1a;
                color: #fff;
                border: none;
            }

            .form-container button {
                background-color: #E50914;
                color: #fff;
                border: none;
                padding: 10px 20px;
                font-size: 16px;
                cursor: pointer;
                margin-right: 10px;
            }

            .form-container a {
                background-color: #E50914;
                color: #fff;
                border: none;
                padding: 10px 20px;
                font-size: 16px;
                cursor: pointer;
                margin-right: 10px;
            }
    </style>
</head>
<body>

    <main>



        <!-- Sección de creación/edición de series -->
        <div class="form-container">
            <h2>Crear Serie</h2>
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div>
                    <label asp-for="SerieID">Nombre de la serie:</label>
                    <input asp-for="SerieID" type="text" id="SerieID" name="SerieID" required>
                    <span asp-validation-for="SerieID" class="text-danger"></span>
                </div>
                <div>
                    <label asp-for="Nombre">Nombre de la serie:</label>
                    <input asp-for="Nombre" type="text" id="name" name="Nombre" required>
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
                <div>
                    <label asp-for="Imagen">Imagen de portada:</label>
                    <input asp-for="Imagen" type="text" id="cover-image" name="Imagen" required>
                    <span asp-validation-for="Imagen" class="text-danger"></span>
                </div>
                <div>
                    <label asp-for="URL">Enlace del video de YouTube:</label>
                    <input asp-for="URL" type="text" id="youtube-link" name="URL" required>
                    <span asp-validation-for="URL" class="text-danger"></span>
                </div>
                <div>
                    <label for="production-company">Productora:</label>
                    <select asp-for="IDproductor" asp-items="@(new SelectList(ViewBag.Productores, "IDproductor","Nombre"))">
                        <!-- Agrega más opciones de productoras -->
                    </select>
                    <span asp-validation-for="IDproductor" class="text-danger"></span>
                </div>
                <div>
                    <label for="primary-genre">Género primario:</label>
                    <select asp-for="IDgenero" asp-items="@(new SelectList(ViewBag.Generos, "IDgenero","Tipo"))">
                        <!-- Agrega más opciones de géneros -->
                    </select>
                    <span asp-validation-for="IDgenero" class="text-danger"></span>
                </div>
                <div>
                    <label for="secondary-genre">Género secundario:</label>
                    <select asp-for="IDgenero2" asp-items="@(new SelectList(ViewBag.Generos, "IDgenero","Tipo"))">
                        <!-- Agrega más opciones de géneros -->
                    </select>
                    <span asp-validation-for="IDgenero2" class="text-danger"></span>
                </div>
                <div>
                    <label for="name">Descripcion:</label>
                    <input asp-for="Descripcion" type="text" id="decripcion" name="Descripcion" required>
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>
                <div>
                    <label for="primary-genre">Categoria :</label>
                    <select asp-for="IDcategoria" asp-items="@(new SelectList(ViewBag.Categorias, "IDcategoria", "Nombre"))">
                        <!-- Agrega más opciones de géneros -->
                    </select>
                    <span asp-validation-for="IDcategoria" class="text-danger"></span>
                </div>
                <div>
                    <a asp-controller="Series" asp-action="index" class="btn btn-primary">Volver</a>
                    <button type="submit" value="Edit">Guardar Cambios</button>
                </div>
            </form>
        </div>
    </main>
</body>
</html>

Miniproyecto/Miniproyecto/Views/Series/Index.cshtml
@model IEnumerable<MiniProyecto.Web.Models.SeriesModel>
<!DOCTYPE html>
<html>
<head>
    <title>Netflix-Style MVC Design</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
            background-color: #1a1a1a;
        }

        header {
            background-color: #E50914;
            color: #fff;
            padding: 20px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        nav ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            display: flex;
        }

        nav li {
            margin-right: 20px;
        }

        nav a {
            color: #fff;
            text-decoration: none;
        }

        main {
            padding: 20px;
            width: 100%;
            box-sizing: border-box;
        }

        .hero {
            background-color: #000;
            color: #fff;
            padding: 100px 20px;
            text-align: center;
        }

            .hero h1 {
                font-size: 48px;
                margin-bottom: 20px;
            }

            .hero p {
                font-size: 24px;
                margin-bottom: 40px;
            }

            .hero button {
                background-color: #E50914;
                color: #fff;
                border: none;
                padding: 10px 20px;
                font-size: 18px;
                cursor: pointer;
            }

        .content {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
            gap: 20px;
        }

        .content-item {
            background-color: #262626;
            color: #fff;
            padding: 20px;
            text-align: center;
        }

            .content-item img {
                max-width: 100%;
                height: auto;
                margin-bottom: 20px;
            }

            .content-item h3 {
                margin-bottom: 10px;
            }

            .content-item p {
                margin-bottom: 20px;
            }

            .content-item button {
                background-color: #E50914;
                color: #fff;
                border: none;
                padding: 10px 20px;
                font-size: 16px;
                cursor: pointer;
            }
         

            .content-series a{
                background-color: #E50914;
                color: #fff;
                border: none;
                padding: 10px 20px;
                font-size: 16px;
                cursor: pointer;

        }

      
    </style>
</head>
<body>
    <main>
        <div class="hero">
            <h1>Series</h1>
            <p>Unlimited movies, TV shows, and more.</p>
            <button>Start Watching</button>
        </div>

        <div class="content">
            @foreach (var item in Model)
            {
                <div class="content-item">
                    <img src="@item.Imagen" alt="Series 2">
                    <h3>@item.Nombre</h3>
                    <p>@item.Descripcion</p>
                    <div class="buttons">
                        <button>Watch Now</button>
                        <a asp-controller="Series" asp-action="Edit" asp-route-id="@item.SerieID" class="btn btn-primary">Editar</a>

                    </div>
                </div>
            
                    }

            <!-- Puedes agregar más contenedores aquí según sea necesario -->
        </div>

        <br/>
        <div class="content-series">
          
                <a asp-controller="Series" asp-action="Create" class="btn btn-primary">Agregar series </a>
            </div>
       
    </main>
</body>
</html>